[package]
name = "symo"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
handlebars = "*"
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
walkdir = "*"
